name: commit HexoBlogSource (Obsidian update)

on:
  push:
    branches:
      - main

jobs:
  submit:
    name: cp and config git
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Obsidian Update"
          fi

      - name: Git clone HexoBlogSource and cp .md file
        working-directory: .
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone https://github.com/WhaleFell/HexoBlogSource ./HexoBlogSource/
          cp -r ./博客文章/_post/* ./HexoBlogSource/source/_posts/
          cd ./HexoBlogSource/
          git add .
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Obsidian Upload!"
          fi

      
  commit:
    needs: submit
    name: commit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./HexoBlogSource
    steps:
      - name: Push to target repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          repository: WhaleFell/HexoBlogSource

    
    
