name: commit HexoBlogSource (Obsidian update)

on:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: git config
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config --global --add safe.directory /github/workspace
          if [[ -n $(git status --porcelain) ]]; then
              git commit -m "Obsidian Update"
          fi

      - name: New Branch to pull
        run: |
          # 切换到原来的 main 分支
          git checkout main

          # 创建一个新分支并切换到该分支
          git checkout -b hexo

          # 移动博客文章/博客文章_post目录到新分支的根目录
          git mv 博客文章/博客文章_post/* .
          git rm -rf 博客文章

          if [[ -n $(git status --porcelain) ]]; then
              git commit -m "Move 博客文章/博客文章_post to new branch"
          fi
          
          

      - name: Push to target repository
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: 博客文章/博客文章_post
          repository: WhaleFell/HexoBlogSource
