name: commit HexoBlogSource (Obsidian update)

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: test
      run: echo "${{ secrets.API_TOKEN_GITHUB }}"

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '博客文章/_post/'
        destination_repo: 'WhaleFell/HexoBlogSource'
        destination_folder: 'source/_posts'
        user_email: 'whalefell9420@outlook.com'
        user_name: 'whalefell9420'
        commit_message: 'Obsidian upload'


    
    
